const TYPESCRIPT_PACKAGE = 'typescript';
const TYPESCRIPT_PACKAGE_JSON = `${TYPESCRIPT_PACKAGE}/package.json`;
const TYPESCRIPT_PREVIEW_PACKAGE = '@typescript/native-preview';
const TYPESCRIPT_PREVIEW_PACKAGE_JSON = `${TYPESCRIPT_PREVIEW_PACKAGE}/package.json`;
const TYPESCRIPT_GO_ISSUE_CODE = 'TSGO';

export {
  TYPESCRIPT_GO_ISSUE_CODE,
  TYPESCRIPT_PACKAGE,
  TYPESCRIPT_PACKAGE_JSON,
  TYPESCRIPT_PREVIEW_PACKAGE,
  TYPESCRIPT_PREVIEW_PACKAGE_JSON,
};
