const TYPESCRIPT_GO_PACKAGE = '@typescript/native-preview';
const TYPESCRIPT_GO_PACKAGE_JSON = `${TYPESCRIPT_GO_PACKAGE}/package.json`;
const TYPESCRIPT_GO_ISSUE_CODE = 'TSGO';

export { TYPESCRIPT_GO_PACKAGE, TYPESCRIPT_GO_PACKAGE_JSON, TYPESCRIPT_GO_ISSUE_CODE };
